---
- name: Remove Docker on Ubuntu server
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: absent

    - name: Remove Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: absent

    - name: Remove Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: absent

    - name: Update apt cache after removing Docker repo
      apt:
        update_cache: yes

    - name: remove Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: absent

    - name: Ensure Docker service is stopped
      service:
        name: docker
        state: stopped
        enabled: yes


